# Generated by Django 5.2.12 on 2026-04-02 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('mentors', '0001_initial'),
        ('organizations', '0001_initial'),
        ('talents', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('opportunity_type', models.CharField(choices=[('internship', 'Internship'), ('micro_project', 'Micro-Project'), ('guided_project', 'Guided Project'), ('full_time', 'Full-Time'), ('part_time', 'Part-Time')], db_index=True, default='internship', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed'), ('filled', 'Filled')], db_index=True, default='draft', max_length=20)),
                ('experience_level', models.CharField(blank=True, help_text='e.g., Entry-level, 1-2 years', max_length=50)),
                ('is_remote', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_paid', models.BooleanField(default=False)),
                ('compensation', models.CharField(blank=True, help_text='e.g., ₦150,000/month, $500 fixed', max_length=100)),
                ('duration', models.CharField(blank=True, help_text='e.g., 3 months, 2 weeks', max_length=100)),
                ('max_applicants', models.PositiveIntegerField(blank=True, help_text='Maximum number of applications to accept', null=True)),
                ('spots_available', models.PositiveIntegerField(default=1, help_text='Number of positions available')),
                ('application_deadline', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities_created', to=settings.AUTH_USER_MODEL)),
                ('mentor', models.ForeignKey(blank=True, help_text='For guided projects posted by mentors', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='mentors.mentorprofile')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='organizations.organization')),
                ('required_skills', models.ManyToManyField(blank=True, related_name='opportunities_requiring', to='core.canonicalskill')),
            ],
            options={
                'verbose_name': 'Opportunity',
                'verbose_name_plural': 'Opportunities',
                'db_table': 'opportunities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(blank=True, help_text='Why are you interested in this opportunity?')),
                ('resume_url', models.URLField(blank=True, help_text='Link to resume (can override profile resume)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewing', 'Reviewing'), ('shortlisted', 'Shortlisted'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], db_index=True, default='pending', max_length=20)),
                ('reviewer_notes', models.TextField(blank=True, help_text='Internal notes from reviewer')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications_reviewed', to=settings.AUTH_USER_MODEL)),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='talents.talentprofile')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='opportunities.opportunity')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'db_table': 'applications',
                'ordering': ['-created_at'],
                'unique_together': {('opportunity', 'talent')},
            },
        ),
    ]
