# Generated by Django 5.2.12 on 2026-05-20 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='opportunity_type',
            field=models.CharField(choices=[('internship', 'Internship'), ('micro_project', 'Micro-Project'), ('guided_project', 'Guided Project')], db_index=True, default='internship', max_length=20),
        ),
    ]
