# Generated by Django 6.0.3 on 2026-06-16 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0002_alter_opportunity_opportunity_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewing', 'Reviewing'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview'), ('offered', 'Offered'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], db_index=True, default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='ApplicationInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_name', models.CharField(help_text='e.g., Technical Interview, Culture Fit', max_length=100)),
                ('scheduled_at', models.DateTimeField()),
                ('meeting_link', models.URLField(blank=True, help_text='Link to the video call')),
                ('notes', models.TextField(blank=True, help_text='Any additional instructions or notes for the talent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='opportunities.application')),
            ],
            options={
                'verbose_name': 'Application Interview',
                'verbose_name_plural': 'Application Interviews',
                'db_table': 'application_interviews',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='opportunities.opportunity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_opportunities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Opportunity',
                'verbose_name_plural': 'Saved Opportunities',
                'db_table': 'saved_opportunities',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'opportunity')},
            },
        ),
    ]
