# Generated by Django 6.0.3 on 2026-06-17 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category'),
        ('opportunities', '0003_alter_application_status_applicationinterview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='core.category'),
        ),
    ]
