# Generated by Django 5.2.12 on 2026-04-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalentSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', help_text='Self-assessed proficiency level', max_length=20)),
                ('years_experience', models.PositiveSmallIntegerField(default=0, help_text='Years of experience with this skill')),
                ('is_primary', models.BooleanField(default=False, help_text='Highlight as a primary/main skill on profile')),
                ('is_endorsed', models.BooleanField(db_index=True, default=False, help_text='Skill has been endorsed/verified by a mentor')),
                ('endorsed_at', models.DateTimeField(blank=True, help_text='When the endorsement was given', null=True)),
                ('endorsement_note', models.TextField(blank=True, help_text='Optional note from the mentor about this endorsement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Talent Skill',
                'verbose_name_plural': 'Talent Skills',
                'db_table': 'talent_skills',
                'ordering': ['-is_primary', '-is_endorsed', 'skill__name'],
            },
        ),
        migrations.CreateModel(
            name='TalentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, help_text="Professional headline (e.g., 'Full Stack Developer | React & Django')", max_length=200)),
                ('bio', models.TextField(blank=True, help_text='About me section - skills, experience, goals')),
                ('education_route', models.CharField(choices=[('university', 'University'), ('polytechnic', 'Polytechnic'), ('bootcamp', 'Bootcamp'), ('self_taught', 'Self-Taught')], db_index=True, default='self_taught', help_text='Primary education/training background', max_length=20)),
                ('institution_name', models.CharField(blank=True, help_text='Name of university, polytechnic, or bootcamp', max_length=255)),
                ('field_of_study', models.CharField(blank=True, help_text="Major/course of study (e.g., 'Computer Science')", max_length=200)),
                ('graduation_year', models.PositiveIntegerField(blank=True, help_text='Year of graduation (or expected)', null=True)),
                ('is_school_verified', models.BooleanField(db_index=True, default=False, help_text='Academic records verified by a School Admin')),
                ('verified_at', models.DateTimeField(blank=True, help_text='When the verification was completed', null=True)),
                ('city', models.CharField(blank=True, help_text='City of residence', max_length=100)),
                ('state', models.CharField(blank=True, help_text='State/region', max_length=100)),
                ('country', models.CharField(default='Nigeria', help_text='Country of residence', max_length=100)),
                ('portfolio_url', models.URLField(blank=True, help_text='Personal portfolio website')),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL')),
                ('github_url', models.URLField(blank=True, help_text='GitHub profile URL')),
                ('resume_url', models.URLField(blank=True, help_text='Resume/CV URL (stored in Supabase Storage)')),
                ('is_available', models.BooleanField(db_index=True, default=True, help_text='Currently looking for opportunities')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_industries', models.ManyToManyField(blank=True, help_text='Industries the talent is interested in', related_name='interested_talents', to='core.canonicalindustry')),
            ],
            options={
                'verbose_name': 'Talent Profile',
                'verbose_name_plural': 'Talent Profiles',
                'db_table': 'talent_profiles',
            },
        ),
    ]
