# Generated by Django 5.2.12 on 2026-04-02 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, help_text="Professional headline (e.g., 'Senior Software Engineer at Google')", max_length=200)),
                ('bio', models.TextField(blank=True, help_text='About the mentor - experience, expertise, mentoring style')),
                ('linkedin_url', models.URLField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('is_accepting_mentees', models.BooleanField(default=True, help_text='Currently accepting new mentees')),
                ('max_mentees', models.PositiveIntegerField(default=5, help_text='Maximum number of mentees at a time')),
                ('is_verified', models.BooleanField(default=False, help_text='Mentor credentials have been verified')),
                ('endorsements_given', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expertise_areas', models.ManyToManyField(blank=True, help_text='Skills the mentor can endorse/teach', related_name='expert_mentors', to='core.canonicalskill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mentor Profile',
                'verbose_name_plural': 'Mentor Profiles',
                'db_table': 'mentor_profiles',
            },
        ),
    ]
