# Generated by Django 5.2.12 on 2026-04-02 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('talents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='talentprofile',
            name='user',
            field=models.OneToOneField(help_text='The user this talent profile belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='talent_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='School Admin who verified this profile', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='talentskill',
            name='endorsed_by',
            field=models.ForeignKey(blank=True, help_text='Mentor who endorsed this skill', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill_endorsements_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='talentskill',
            name='skill',
            field=models.ForeignKey(help_text='The canonical skill', on_delete=django.db.models.deletion.CASCADE, related_name='talent_skills', to='core.canonicalskill'),
        ),
        migrations.AddField(
            model_name='talentskill',
            name='talent',
            field=models.ForeignKey(help_text='The talent profile', on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='talents.talentprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='talentskill',
            unique_together={('talent', 'skill')},
        ),
    ]
