# Generated by Django 5.2.12 on 2026-04-02 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('talents', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('school_type', models.CharField(choices=[('university', 'University'), ('polytechnic', 'Polytechnic'), ('bootcamp', 'Bootcamp'), ('other', 'Other')], default='university', max_length=20)),
                ('website_url', models.URLField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Nigeria', max_length=100)),
                ('is_verified', models.BooleanField(default=False, help_text='School has been verified by SkillBridge')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admins', models.ManyToManyField(blank=True, related_name='administered_schools', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
                'db_table': 'schools',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudentRosterRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matriculation_number', models.CharField(db_index=True, help_text="Student's matriculation/registration number", max_length=50)),
                ('email', models.EmailField(blank=True, help_text="Student's school email", max_length=254)),
                ('full_name', models.CharField(blank=True, help_text="Student's name as per school records", max_length=255)),
                ('department', models.CharField(blank=True, help_text='Department/Faculty', max_length=200)),
                ('course_of_study', models.CharField(blank=True, help_text='Course/Program of study', max_length=200)),
                ('enrollment_year', models.PositiveIntegerField(blank=True, help_text='Year of enrollment', null=True)),
                ('expected_graduation_year', models.PositiveIntegerField(blank=True, null=True)),
                ('graduation_year', models.PositiveIntegerField(blank=True, help_text='Actual graduation year (if graduated)', null=True)),
                ('is_graduated', models.BooleanField(default=False)),
                ('cgpa', models.DecimalField(blank=True, decimal_places=2, help_text='Cumulative GPA if school provides it', max_digits=3, null=True)),
                ('has_consented', models.BooleanField(db_index=True, default=False, help_text='Student has consented to data sharing')),
                ('consented_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_records', to='schools.school')),
                ('talent_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_records', to='talents.talentprofile')),
            ],
            options={
                'verbose_name': 'Student Roster Record',
                'verbose_name_plural': 'Student Roster Records',
                'db_table': 'student_roster_records',
                'unique_together': {('school', 'matriculation_number')},
            },
        ),
    ]
