# Generated by Django 5.2.12 on 2026-05-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_type', models.CharField(choices=[('talent', 'Talent'), ('school', 'School')], db_index=True, max_length=32)),
                ('subject_id', models.PositiveIntegerField(db_index=True)),
                ('kind', models.CharField(choices=[('trust_score', 'Trust Score'), ('skill_roadmap', 'Skill Roadmap'), ('curriculum_alignment', 'Curriculum Alignment')], db_index=True, max_length=32)),
                ('payload', models.JSONField(help_text='The computed insight, shape depends on kind.')),
                ('recomputed_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'AI Insight',
                'verbose_name_plural': 'AI Insights',
                'db_table': 'ai_insights',
                'indexes': [models.Index(fields=['subject_type', 'subject_id', 'kind'], name='ai_insights_subject_2ba7e1_idx')],
                'unique_together': {('subject_type', 'subject_id', 'kind')},
            },
        ),
    ]
