# Generated by Django 5.2.12 on 2026-05-18 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0001_initial'),
        ('talents', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorshipRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('ended', 'Ended')], db_index=True, default='active', max_length=20)),
                ('focus_area', models.CharField(blank=True, help_text="What the mentee wants to learn (e.g. 'System design for backend roles')", max_length=255)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorships', to='mentors.mentorprofile')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorships', to='talents.talentprofile')),
            ],
            options={
                'verbose_name': 'Mentorship Relationship',
                'verbose_name_plural': 'Mentorship Relationships',
                'db_table': 'mentorship_relationships',
                'ordering': ['-started_at'],
                'unique_together': {('mentor', 'talent')},
            },
        ),
        migrations.CreateModel(
            name='MentorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_for', models.DateTimeField(db_index=True)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=30)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], db_index=True, default='scheduled', max_length=20)),
                ('topic', models.CharField(blank=True, max_length=255)),
                ('private_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='mentors.mentorshiprelationship')),
            ],
            options={
                'verbose_name': 'Mentor Session',
                'verbose_name_plural': 'Mentor Sessions',
                'db_table': 'mentor_sessions',
                'ordering': ['-scheduled_for'],
            },
        ),
        migrations.CreateModel(
            name='MenteeActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('skill_added', 'Skill Added'), ('skill_endorsed', 'Skill Endorsed'), ('application_submitted', 'Application Submitted'), ('application_accepted', 'Application Accepted'), ('project_shipped', 'Project Shipped'), ('blocker_reported', 'Blocker Reported'), ('note', 'General Note')], db_index=True, max_length=32)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='mentors.mentorshiprelationship')),
            ],
            options={
                'verbose_name': 'Mentee Activity',
                'verbose_name_plural': 'Mentee Activities',
                'db_table': 'mentee_activities',
                'ordering': ['-occurred_at'],
            },
        ),
    ]
