# Generated by Django 5.2.12 on 2026-05-19 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google'), ('apple', 'Apple')], db_index=True, max_length=16)),
                ('subject', models.CharField(help_text="The `sub` claim from the provider's ID token. Stable across sessions.", max_length=255)),
                ('last_email', models.EmailField(blank=True, max_length=254)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_identities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OAuth Identity',
                'verbose_name_plural': 'OAuth Identities',
                'db_table': 'oauth_identities',
                'unique_together': {('provider', 'subject')},
            },
        ),
    ]
