# Generated by Django 5.2.12 on 2026-05-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_oauthidentity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verification_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the last verification email was sent. Drives resend rate-limiting.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(db_index=True, default=False, help_text='True once the user has clicked the verification link.'),
        ),
    ]
