# Generated by Django 5.2.12 on 2026-04-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CanonicalIndustry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Industry name (e.g., 'FinTech', 'HealthTech', 'EdTech')", max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the industry')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this industry is available for selection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Industry',
                'verbose_name_plural': 'Industries',
                'db_table': 'canonical_industries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CanonicalSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Skill name (e.g., 'Python', 'React', 'Data Analysis')", max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=100, unique=True)),
                ('category', models.CharField(blank=True, db_index=True, help_text="Skill category (e.g., 'Programming', 'Design', 'Marketing', 'Data')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional description of the skill')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this skill is available for selection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'db_table': 'canonical_skills',
                'ordering': ['category', 'name'],
            },
        ),
    ]
